oncologia/views/auth.py
from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    session,
    url_for,
)

from oncologia.extensions.models import User
from oncologia.forms import LoginForm

bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/login", methods=["POST", "GET"])
def login():
    form = LoginForm()
    if session.get("user_id"):
        return redirect(url_for("home.index"))

    def POST():
        if form.validate_on_submit():
            user = User.query.filter_by(username=form.username.data).first()
            if not user or not user.checkpw(form.password.data):
                flash("Usuário e/ou Senha inválidos", "error")
                return
            session["user_id"] = getattr(user, "id")
            flash("Login efetuado com sucesso", "success")
            return redirect(url_for("home.index"))

    returned = locals().get(request.method, lambda: None)()
    if returned:
        return returned
    return render_template("auth/login.html", form=form)


@bp.route("/logout")
def logout():
    session.pop("user_id")
    return redirect(url_for("auth.login"))

oncologia/views/patient.py
from flask import Blueprint, flash, redirect, render_template, request, url_for

from oncologia.extensions.database import db
from oncologia.extensions.models import (
    DiagnosisCharacterization,
    DiagnosisLocation,
    EntryPoin,
    EntryTeam,
    ExamType,
    Patient,
    Pendency,
    PendencyStatus,
    PendencyType,
    PhoneNumber,
    Status,
    StatusType,
    TumorCharacterization,
    TumorGroup,
)
from oncologia.forms import PatientForm, PendencyForm
from oncologia.utils import get_status_type_form, login_required

bp = Blueprint("patient", __name__, url_prefix="/patient")


@bp.route("/")
@login_required
def profile():
    patient_id = request.args.get("id")

    patient = Patient.query.filter_by(ghc=patient_id).first()
    if not patient:
        flash("Paciente com ID especificado não encontrado.", "error")
        return redirect(url_for("home.index"))

    return render_template("/patient/profile.html", patient=patient)


@bp.route("/add-pendency", methods=["GET", "POST"])
@login_required
def create_pendency():
    patient_id = request.args.get("id")

    form = PendencyForm()

    patient = Patient.query.get(patient_id)  # Obtém o paciente pelo ID
    if not patient:
        flash("Paciente não encontrado.", "error")
        return redirect(url_for("home.index"))

    def POST():
        if form.validate_on_submit():
            pendency_type = PendencyType.query.filter_by(
                id=form.type_ad.data
            ).first()
            if not pendency_type:
                pendency_type = PendencyType(
                    name=form.type_ad.data  # type: ignore [data-isnt-none]
                )

            status_name = form.status.data

            new_pendency = Pendency(
                type=pendency_type,
                due_date=form.date.data,
                description=form.description.data,
                status=PendencyStatus(status_name),
                patient_id=patient_id,
            )

            db.session.add(new_pendency)
            db.session.commit()
            flash("Pendência adicionada com sucesso!", "success")
            return redirect(url_for("patient.profile", id=patient_id))

    returned = locals().get(request.method, lambda: None)()
    if returned:
        return returned
    return render_template(
        "patient/create_pendency.html", form=form, patient_id=patient_id
    )


@bp.route("/create", methods=["POST", "GET"])
@login_required
def create():
    form = PatientForm()

    def POST():
        if not form.validate_on_submit():
            flash("Erro ao adicionar paciente", "error")
            return

        # Tumor Characterization
        tumor_group = TumorGroup.query.filter_by(
            id=form.tumor_characterization.tumor_group.data
        ).first()

        if not tumor_group:
            tumor_group = TumorGroup(
                name=form.tumor_characterization.tumor_group.data
            )
        tumor_characterization_data = {
            k: v for k, v in form.tumor_characterization.data.items()
        }
        tumor_characterization_data.update({"tumor_group": tumor_group})
        tumor_characterization = TumorCharacterization(
            **tumor_characterization_data
        )

        # Diagnosis Characterization
        diagnosis_characterization_data = {
            k: v for k, v in form.diagnosis_characterization.data.items()
        }
        entry_poin = EntryPoin.query.filter_by(
            id=form.diagnosis_characterization.entry_poin.data
        ).first()
        if not entry_poin:
            entry_poin = EntryPoin(
                name=form.diagnosis_characterization.entry_poin.data
            )

        entry_team = EntryTeam.query.filter_by(
            id=form.diagnosis_characterization.entry_team.data
        ).first()
        if not entry_team:
            entry_team = EntryTeam(
                name=form.diagnosis_characterization.entry_team.data
            )

        diagnosis_exam = ExamType.query.filter_by(
            id=form.diagnosis_characterization.diagnosis_exam.data
        ).first()
        if not diagnosis_exam:
            diagnosis_exam = ExamType(
                name=form.diagnosis_characterization.diagnosis_exam.data
            )

        diagnosis_location = DiagnosisLocation(
            int(form.diagnosis_characterization.diagnosis_location.data)
        )  # TODO: dont trust in this conversion.

        diagnosis_characterization_data.update(
            {
                "entry_poin": entry_poin,
                "entry_team": entry_team,
                "diagnosis_exam": diagnosis_exam,
                "diagnosis_location": diagnosis_location,
            }
        )

        diagnosis_characterization = DiagnosisCharacterization(
            **diagnosis_characterization_data
        )

        # Pacient
        patient_data = {
            k: v
            for k, v in form.data.items()
            if k
            not in (
                "tumor_characterization",
                "diagnosis_characterization",
                "phone_1",
                "phone_2",
            )
        }

        phones = [
            PhoneNumber(**form.data[k])
            for k in form.data.keys()
            if k.startswith("phone") and form.data[k]["number"]
        ]

        patient_data.update(
            {
                "phones": phones,
                "tumor_characterization": tumor_characterization,
                "diagnosis_characterization": diagnosis_characterization,
            }
        )

        patient = Patient(**patient_data)
        db.session.add(patient)
        db.session.commit()
        flash("Paciente adicionado com sucesso", "success")

    returnerd = locals().get(request.method, lambda: None)()
    return (
        render_template("patient/create.html", form=form)
        if not returnerd
        else returnerd
    )


@bp.route("/change-status/<int:patient_id>", methods=["POST", "GET"])
@login_required
def change_status(patient_id: int):
    patient = Patient.query.filter_by(ghc=patient_id).first()
    if not patient:
        flash("Paciente com ID especificado não encontrado.", "error")
        return redirect(url_for("home.index"))

    action = request.args.get("action", "")

    def submit_status():
        status_type = request.args.get("status_type")
        if not status_type:
            flash("Selecione primeiro um tipo de status.", "error")
            return redirect(
                url_for("patient.change_status", patient_id=patient_id)
            )

        try:
            status_type = StatusType(status_type)
        except ValueError:
            flash("Tipo de Status inválido, escolha outro.", "error")
            return redirect(
                url_for("patient.change_status", patient_id=patient_id)
            )

        form = get_status_type_form(status_type)()

        if form.validate_on_submit():
            new_status = Status(type=status_type, **form.data)
            patient.statuses.append(new_status)
            db.session.commit()
            flash("Status adicionado com sucesso!", "success")
            return redirect(url_for("patient.profile", id=patient_id))

        return render_template(
            "patient/change_status.html", patient=patient, form=form
        )

    func = locals().get(action, lambda: None)
    returned = func()
    if returned:
        return returned

    return render_template(
        "patient/change_status.html",
        patient=patient,
        possible_status=StatusType.__members__.values(),
    )

oncologia/templates/components/flash_messages.html
{% macro show() %}

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}" role="alert">
      <span>{{ message }}</span>
    </div>
    {% endfor %}
  {% endif %}
{% endwith %}

{% endmacro %}

oncologia/templates/components/navbar.html
{% macro show() %}
<div class="navbar glass">
    <div class="flex-1">
        <a class="btn btn-ghost text-xl">{{ config.APP_NAME }}</a>
    </div>
    <div class="flex-none gap-3 justify-around">
        {% with navbar_pages = get_navigation_pages() %}
        <!--  -->
        {% for endpoint, name, icon in navbar_pages %}
        <a href="{{ url_for(endpoint) }}" class="flex gap-2 btn btn-outline">
            <i data-lucide="{{ icon }}"></i>
            {{ name }}
        </a>
        {% endfor %}
        <!--  -->
        {% endwith %}
        <!--  -->
        {% if session.user_id %}

        <a href="{{ url_for('auth.logout') }}" class="btn btn-accent btn-outline">
            <i data-lucide="log-out"></i>
            Sair
        </a>
        {% else %}
        <a href="{{ url_for('auth.login') }}" class="btn btn-accent btn-outline">
            <i data-lucide="lock"></i>
            Login
        </a>
        {% endif %}
    </div>
</div>
{% endmacro %}

oncologia/templates/components/pagination.html
{% macro show(pagination) %}
<!--  -->
{% if pagination.pages > 1 %}
<div class="join">
  {% if pagination.has_prev %}
  <a
    class="join-item btn"
    href="?q={{ request.args.get('q', '') }}&p={{ pagination.prev_num }}"
  >
    Anterior
  </a>
  {% endif %}
  <!-- -->
  {% for page in pagination.iter_pages() %}
  <!--  -->
  {% if page %}
  <a
    class="join-item btn {% if page == pagination.page %}btn-primary{% endif %}"
    href="?q={{ request.args.get('q', '') }}&p={{ page }}"
  >
    {{ page }}
  </a>
  {% else %}
  <span class="join-item btn">...</span>
  {% endif %}
  <!--  -->
  {% endfor %}
  <!--  -->
  {% if pagination.has_next %}
  <a
    class="join-item btn"
    href="?q={{ request.args.get('q', '') }}&p={{ pagination.next_num }}"
  >
    Próxima
  </a>
  {% endif %}
</div>
{% endif %}
<!--  -->
{% endmacro %}

oncologia/templates/components/patient_card.html
{% import "components/status.html" as status %} {% macro render(patient) %}
<div class="card bg-base-200 shadow-xl">
  <div class="card-body">
    <h2 class="card-title text-primary text-3xl">
      <i data-lucide="circle-user" class="w-10 h-10"></i>
      Perfil do Paciente
    </h2>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      <h3
        class="flex items-center gap-2 text-accent text-xl mt-4 col-span-1 md:col-span-2 lg:col-span-3"
      >
        <i data-lucide="info"></i>
        Informações
      </h3>
      <p><strong>Nome:</strong> {{ patient.name }}</p>
      <p><strong>GHC:</strong> {{ patient.ghc }}</p>
      <p><strong>Nascimento:</strong> {{ patient.birthday.strftime('%d/%m/%Y') }}</p>
      <p><strong>Sexo:</strong> {{ patient.gender }}</p>
      <p><strong>Raça:</strong> {{ patient.race }}</p>
      <p><strong>CPF:</strong> {{ patient.cpf or 'N/A' }}</p>
      <p><strong>Endereço:</strong> {{ patient.address or 'N/A' }}</p>
      <p><strong>Cidade:</strong> {{ patient.city }}</p>
      <p><strong>Estado:</strong> {{ patient.state }}</p>
      <p><strong>CNS:</strong> {{ patient.cns or 'N/A' }}</p>
    </div>

    <h3 class="flex items-center gap-2 text-accent text-xl mt-4">
      <i data-lucide="book-user"></i>
      Contatos ({{ patient.phones | length}})
    </h3>
    {% for phone in patient.phones %}
    <p class="flex">
      {{ phone.number }} (WhatsApp:
      <span
        class="tooltip tooltip-right tooltip-primary"
        data-tip="Este número {{'' if phone.is_wpp else 'não'}} está no WhatsApp"
      >
        <i
          data-lucide="{{ clsx(['check-circle', phone.is_wpp], ['x-circle', not phone.is_wpp]) }}"
          class="{{ clsx(['text-green-500', phone.is_wpp], ['text-red-500', not phone.is_wpp], 'ml-2') }}"
        ></i> </span
      >)
    </p>
    {% endfor %}

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      <h3
        class="flex items-center gap-2 text-accent text-xl mt-4 col-span-1 md:col-span-2 lg:col-span-3"
      >
        <i data-lucide="stethoscope"></i>
        Caracterização do Tumor
      </h3>
      <p>
        <strong>Local do Tumor Primário:</strong>
        {{ patient.tumor_characterization.tumor_group.name }}
      </p>
      <p>
        <strong>Tipo Histológico do Tumor Primário (CID):</strong>
        {{ patient.tumor_characterization.histological_type_primary_tumor }}
      </p>
      <p>
        <strong>Estadiamento (TNM):</strong>
        {{ patient.tumor_characterization.staging }}
      </p>
      <p>
        <strong>Localização da Metástase à Distância:</strong>
        {{ patient.tumor_characterization.location_distant_metastasis }}
      </p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      <h3
        class="flex items-center gap-2 text-accent text-xl mt-4 col-span-1 md:col-span-2 lg:col-span-3"
      >
        <i data-lucide="activity"></i>
        Caracterização do Diagnóstico
      </h3>
      <p>
        <strong>Data 1ª Consulta no Hospital:</strong>
        {{ patient.diagnosis_characterization.primary_date_consult.strftime('%d/%m/%Y') }}
      </p>
      <p>
        <strong>Porta de Entrada:</strong>
        {{ patient.diagnosis_characterization.entry_poin.name }}
      </p>
      <p>
        <strong>Equipe de Entrada:</strong>
        {{ patient.diagnosis_characterization.entry_team.name }}
      </p>
      <p>
        <strong>Data do Diagnóstico:</strong>
        {{ patient.diagnosis_characterization.diagnosis_date.strftime('%d/%m/%Y') }}
      </p>
      <p>
        <strong>Local do Diagnóstico:</strong>
        {{ translator(patient.diagnosis_characterization.diagnosis_location.name) }}
      </p>
      <p>
        <strong>Exame no Diagnóstico:</strong>
        {{ patient.diagnosis_characterization.diagnosis_exam.name }}
      </p>
    </div>

    <h3 class="flex items-center gap-2 text-accent text-xl mt-4">
      <i data-lucide="heart-pulse"></i>
      Status do Paciente
    </h3>
      {{ status.render(patient.statuses[0]) }}

    <br />
    <div class="card-actions justify-end">
      <a href="#" class="btn btn-accent">
        <i data-lucide="edit"></i>
        Editar Perfil
      </a>
      <a
        href="{{ url_for('patient.create_pendency', id=patient.ghc) }}"
        class="btn btn-primary"
      >
        <i data-lucide="plus"></i>
        Adicionar Pendência</a
      >
      <a
        href="{{ url_for('patient.change_status', patient_id=patient.ghc) }}"
        class="btn btn-secondary"
      >
        <i data-lucide="settings-2"></i>
        Mudar Status</a
      >
    </div>
  </div>
</div>
{% endmacro %}

oncologia/templates/components/pendency.html
{% macro card(pendency) %}
<div class="card w-full bg-neutral text-neutral-content" id="card-{{ pendency.id }}">
    <div class="card-body items-center text-center">
        <h2 class="card-title">
            {{ pendency.type.name }} - {{ pendency.due_date.strftime("%d/%m/%Y") }}
        </h2>
        <p>{{ pendency.description }}</p>
        <div
            class="tooltip tooltip-bottom tooltip-info"
            data-tip="Ver paciente {{ pendency.patient.name }}"
        >
            <a
                href="{{ url_for('patient.profile', id=pendency.patient.ghc) }}"
                class="btn btn-accent"
                target="_blank"
            >
                <i data-lucide="circle-user"></i>
                {{ pendency.patient.name }} - {{ pendency.patient.ghc }}
            </a>
        </div>
        <div class="card-actions justify-end mt-3">
            <button class="btn btn-primary" id="btn-yes-{{ pendency.id }}">
                <i data-lucide="party-popper"></i>
                Compareceu
            </button>
            <button class="btn btn-error" id="btn-not-{{ pendency.id }}">
                <i data-lucide="x"></i>
                Não Compareceu
            </button>
        </div>
    </div>
    <script>
        setCardActions("{{ pendency.id }}")
    </script>
</div>
{% endmacro %}

<!-- Script -->
{% macro script() %}
<script>
    const setCardActions = (card_id) => {
        const card = document.getElementById(`card-${card_id}`)
        const btnYes = document.getElementById(`btn-yes-${card_id}`)
        const btnNot = document.getElementById(`btn-not-${card_id}`)
        const endpoint = `/api/pendency/${card_id}`

        const markPendency = async (status) => {
            const res = await fetch(endpoint, {
                method: "PUT",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({ status }),
            })

            const data = await res.json()
            return data
        }

        btnYes.addEventListener("click", async () => {
            btnYes.disabled = true
            const data = await markPendency(2) // done
            if (data.status) {
                setToast("Pendência marcada como concluída!")
                card.remove()
            } else {
                setToast("Erro ao marcar pendência como concluída...", "warning")
                btnYes.disabled = false
            }
        })

        btnNot.addEventListener("click", async () => {
            btnNot.disabled = true
            const data = await markPendency(3) // canceled
            if (data.status) {
                setToast("Pendência marcada como cancelada!")
                card.remove()
            } else {
                setToast("Erro ao marcar pendência como cancelada...", "warning")
                btnNot.disabled = false
            }
        })
    }
</script>
{% endmacro %}

oncologia/templates/components/status.html
<!--  -->
{% macro render(status) %}
<h3 class="flex items-center gap-2 text-lg my-4 col-span-1 md:col-span-2 lg:col-span-3">
  <i data-lucide="candlestick-chart"></i>
  {{ status.type.value }}
</h3>

<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
  {% for field in status_fields(status.type) %}
  <p><strong>{{ field.name }}:</strong> {{ field.getter(status) }}</p>
  {% endfor %}
</div>
<!--  -->
{% endmacro %}

oncologia/templates/components/toast.html
{% macro script() %}
<script>
  const toast = document.getElementById("toast")
  const setToast = (message, category = "info") => {
    const div = document.createElement("div")
    div.classList.add("alert", `alert-${category}`)
    div.innerHTML = message
    toast.appendChild(div)
    setTimeout(() => div.remove(), 3000)
  }
</script>
{% endmacro %}

<!-- Show -->
{% macro show() %}
<div id="toast" class="toast toast-bottom toast-end"></div>
{% endmacro %}